# Logger Config 10011      10049

logging:
  level:
    cn.cuptec.avr: debug
    org.springframework.security: debug

server:
  port: 10011

spring:
  application:
    name: faros
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:Ctm@_2017}
      url: jdbc:mysql://${MYSQL-HOST:47.103.45.124}:${MYSQL-PORT:3306}/${MYSQL-DB:faros4}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  redis:
    database: 2
    port: 6379
    password: Ctm@_2017
    host: ${REDIS-HOST:47.103.45.124}
    lettuce:
      pool:
        # 连接池最大连接数，负值表示没有限制
        max-active: 8
        # 连接池最大阻塞事件，负值表示没有限制
        max-wait: -1ms
        # 连接池最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeEnumsPackage: cn.cuptec.faros.common.web.enums
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 关闭日志打印
  global-config:
    banner: false
    db-config:
      db-type: mysql
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

file-upload:
  path: D:\imgs

wx:
  #测试购买公众号
  mp:
    appId: wxbd00156e33ccca64
    secret: 328612338fd922f3be1c49b20b945427
    token: weixin
  #模版消息url
  mpurl:
    sendTopic: s4SMlZMpXSeml9lMfaHG8mm1kv4TW5ga77giTfTj2Q8
    sendLiveQrCodeNotice: UsLUYgFGFqvv2FEl4UeHa-aGi_kvUF5Rl1zrkRGerMc
    sendSubNotice: vrvWwdbXQQmNK8WUl0ifvOhdTbkQJpsi9tbd3G6tU3Q
    paySuccessNotice: 5Ndu_U1Fk1FU_MzpKAfGk_MPLzeOAt-k9vKoi0vla3U
    paySuccessNoticeSalesman: 5Ndu_U1Fk1FU_MzpKAfGk_MPLzeOAt-k9vKoi0vla3U
    shipNotice: Ul8a5rf6riSiO80b1BuOaksOFG7khd9B7mYu-FU8IvU
    refundNotice: mUMXA9io48MGPOIdDkV76nPkguwpPxMwC4zNqe0zZI0
    faPiaoNotice: vihvFXjUhGN7zS81S1QVpJhRINr_yDY0Z53-EICtMg4
    sendFollowUpPlanNotice: 6poffRuNczUIuX8ko5-ZZavh-lVETDkQerlcSPh-dA8
    sendDoctorUrlTip: Zczeadboli73nUiTiMMOyPGn9RGHpdUNppd1dswTCiM
    sendDoctorTip: D6RhGZWd59e4-_yJYMS-3fDi-Xl-OhKo91iG84Hs-RY
    patientAddDoctor: 42O-AVZh8M2Mm5MdrtsxlJhIBpiWz1Gvymq6xDEYLxo
  #测试公众号张伦本地测试
  mp1:
    appId: wxed6151fe3094bbd0
    secret: 1539391f5e68b8901714099c40d6ca4d
    token: weixin
    #小程序
  ma:
    #测试购买小程序
    app-id: wx347d83ad4078ede4
    secret: 8ec2ecd62adc7f6b544451376ccca90f
  ma1:
    #下肢训练小程序
    app-id: wx5e46dffdc68e71cd
    secret: 0fe69b2bd8709e94ba9d9e547cc212fc

cup:
  sms:
    accessKeyId: LTAIvHPdRBZFbUHk
    accessKeySecret: LwjfN1jCj1r7lp1RohspJyOm97wmmE
    signName: 易网健
    expireTime: 180
    loginTemplate: SMS_175581222

sms:
  accessKeyId: LTAIvHPdRBZFbUHk
  accessKeySecret: LwjfN1jCj1r7lp1RohspJyOm97wmmE
  signName: 易网健
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tB3NzFo7YWq7HLSBFSn
  accessKeySecret: SRZfJexAWs7QdrSt45aey8Jg6PqWTm
  bucket: ewj-pharos
tx:
  im:
    sdkAppID: 1400561339
    accessKeySecret: aa525b5eb4312ec1998d03d657a8b4457199583322d15cfacf337b525f718d53
    admin: administrator

com:
  payUrl: https://api.redadzukibeans.com/weChat/wxpayother/testotherOrder
  refundUrl: https://api.redadzukibeans.com/weChat/wxpayother/testotherRefundOrder
  url: https://api.jhxiao-school.com/
  biz: Mzk0MjQ5MzY2NQ==
  chatServer: 8018
alipay:
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqnvbm/slPh1TKRx3u/GpNbwCObJACqnSfsj72hEHlB8mDMivA6GvYpxbct1gGqQKknBZntbq4pgqY48ugDVFfVqbV14xKA74KGoMK0k87mHTSkSnXURsUXmgAnM7h44hhsPWAFlxUhJT+m6gt51+ltA4txigMXcvJtTSapJHU7nyzNFZ7fXqSzLQ1ZIiVgx8zuVGAnDbWimwd4O8+yVrxYuic2ZOO+2Qt5s91TwtTMOasfcXv/S4TB82v8t6g9gWm9riY9RvJ6gEucZkMkQvV4etU8s4CEIzud9ybqUOfhZguocSXMtTxHU3PdM1HhzktMj68cgP50vgDAdGBt9CTQIDAQAB
  appId: 2021003190689317
  gateway: https://openapi.alipay.com/gateway.do
  appPrivateKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtLUzH7+Zpld6nyxCOcZ+tQVxVIpGfg3pmV34Ky1Bz6v/fVGbt7ZVFPc004vmPwToPd4FURzXI9+udtzE+QNLGdA7wqRES65S49F6CyVNcfELbGAWpG6F5OkI6ZPPj0TYL3BYUm0CwuoxR8mSmlUtwh5FGe9EWvOJdw+rgLtXl6l2gd+YSzy3tD9fPfKVdRLNxZLUE96lQRlf+R0GraxRu1mvg9hbxVBT8HD3GSW8Rfdy94cUkLKDazLzucw74K60u5OGBXkpc5fA4GI2x6rqUt4nbxuJI2yJBFF7CnWEpdsYhXuClhvAqlMn02prepCck0RJZrT1T/oL6W9k+xJjRwIDAQAB