# Logger Config 10011      10049

logging:
  level:
    cn.cuptec.avr: debug
    org.springframework.security: debug

server:
  port: 10049

spring:
  application:
    name: faros
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL-USER:root}
      password: ${MYSQL-PWD:Ctm@_2017}
      url: jdbc:mysql://${MYSQL-HOST:47.103.45.124}:${MYSQL-PORT:3306}/${MYSQL-DB:faros3}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
  redis:
    database: 3
    port: 6379
    password: Ctm@_2017
    host: ${REDIS-HOST:47.103.45.124}
    lettuce:
      pool:
        # 连接池最大连接数，负值表示没有限制
        max-active: 8
        # 连接池最大阻塞事件，负值表示没有限制
        max-wait: -1ms
        # 连接池最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeEnumsPackage: cn.cuptec.faros.common.web.enums
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 关闭日志打印
  global-config:
    banner: false
    db-config:
      db-type: mysql
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

file-upload:
  path: D:\imgs

wx:
  #公众号
  mp:
    appId: wx0ed9d77369636eb3
    secret: 31afe6666a17a2fbe3dd44ae6d09f7ab
    token: weixin
    #模版消息url
  mpurl:
    sendTopic: s4SMlZMpXSeml9lMfaHG8mm1kv4TW5ga77giTfTj2Q8
    sendLiveQrCodeNotice: UsLUYgFGFqvv2FEl4UeHa-aGi_kvUF5Rl1zrkRGerMc
    sendSubNotice: A5D2HXLY7MnU72NaeDqcQBwCYR3Ldg-8plClkQL8OGE
    paySuccessNotice: mzXslzSjZiMhCQJ6MQi_bcDJOVbDLl6sfLn6u_0gocI
    paySuccessNoticeSalesman: mzXslzSjZiMhCQJ6MQi_bcDJOVbDLl6sfLn6u_0gocI
    shipNotice: 4bNAEvxGtvR3itx2X6SzUOBiU8wtmby9tdEOhGU5a3I
    refundNotice: XAJp_620LIdi6otX14W1dLSrYSpuJ_txhuusVoNIv5k
    faPiaoNotice: cYvxMNdH8IOSrLlDCaQ9g-Z8MlCpikBMLi0mvR-9yk0
    sendFollowUpPlanNotice: hqiXa8OXHi3w4BbJF2RaXiVLWbtgTRPi_CQNhFAwa60
    sendDoctorUrlTip: I0dnOwCdpMux-CjWwjsuYPtNhZPaBTA8lkH4lfOgFSs
    sendDoctorTip: JS1GcbXs_Tm28-HnzuStvnDTbLxtL71wxdWaZ-wpnd0
    patientAddDoctor: Y3MxxxKiLCCqf6D2qn1nJwYOlKU2pf2_zFy0cz_YEcs
  #测试公众号
  mp1:
    appId: wxed6151fe3094bbd0
    secret: 1539391f5e68b8901714099c40d6ca4d
    token: weixin
    #小程序
  ma:
    #购买小程序
    app-id: wxad59cd874b45bb96
    secret: d5bc744d1fd9411e159e369f5ba7199d
  ma1:
    #下肢训练小程序
    app-id: wx5e46dffdc68e71cd
    secret: 0fe69b2bd8709e94ba9d9e547cc212fc

cup:
  sms:
    accessKeyId: LTAIvHPdRBZFbUHk
    accessKeySecret: LwjfN1jCj1r7lp1RohspJyOm97wmmE
    signName: 易网健
    expireTime: 180
    loginTemplate: SMS_175581222

sms:
  accessKeyId: LTAIvHPdRBZFbUHk
  accessKeySecret: LwjfN1jCj1r7lp1RohspJyOm97wmmE
  signName: 易网健
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tB3NzFo7YWq7HLSBFSn
  accessKeySecret: SRZfJexAWs7QdrSt45aey8Jg6PqWTm
  bucket: ewj-pharos
tx:
  im:
    sdkAppID: 1400561339
    accessKeySecret: aa525b5eb4312ec1998d03d657a8b4457199583322d15cfacf337b525f718d53
    admin: administrator

com:
  url: https://pharos3.ewj100.com/
  payUrl: https://api.redadzukibeans.com/weChat/wxpayother/otherOrder
  refundUrl: https://api.redadzukibeans.com/weChat/wxpayother/otherRefundOrder
  chatServer: 8098

alipay:
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqnvbm/slPh1TKRx3u/GpNbwCObJACqnSfsj72hEHlB8mDMivA6GvYpxbct1gGqQKknBZntbq4pgqY48ugDVFfVqbV14xKA74KGoMK0k87mHTSkSnXURsUXmgAnM7h44hhsPWAFlxUhJT+m6gt51+ltA4txigMXcvJtTSapJHU7nyzNFZ7fXqSzLQ1ZIiVgx8zuVGAnDbWimwd4O8+yVrxYuic2ZOO+2Qt5s91TwtTMOasfcXv/S4TB82v8t6g9gWm9riY9RvJ6gEucZkMkQvV4etU8s4CEIzud9ybqUOfhZguocSXMtTxHU3PdM1HhzktMj68cgP50vgDAdGBt9CTQIDAQAB
  appId: 2021003190689317
  gateway: https://openapi.alipay.com/gateway.do
  appPrivateKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtLUzH7+Zpld6nyxCOcZ+tQVxVIpGfg3pmV34Ky1Bz6v/fVGbt7ZVFPc004vmPwToPd4FURzXI9+udtzE+QNLGdA7wqRES65S49F6CyVNcfELbGAWpG6F5OkI6ZPPj0TYL3BYUm0CwuoxR8mSmlUtwh5FGe9EWvOJdw+rgLtXl6l2gd+YSzy3tD9fPfKVdRLNxZLUE96lQRlf+R0GraxRu1mvg9hbxVBT8HD3GSW8Rfdy94cUkLKDazLzucw74K60u5OGBXkpc5fA4GI2x6rqUt4nbxuJI2yJBFF7CnWEpdsYhXuClhvAqlMn02prepCck0RJZrT1T/oL6W9k+xJjRwIDAQAB